name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve? What pain point does it address?
      placeholder: Describe the problem or limitation you're experiencing...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: Describe your proposed feature or enhancement...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or workarounds you've considered
      placeholder: What other approaches have you considered?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Important for my use case
        - Critical - Blocking my usage
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall under?
      options:
        - UI/UX - User interface or user experience improvements
        - Performance - Speed, memory, or efficiency improvements
        - Functionality - New features or capabilities
        - Integration - Integration with other tools or services
        - Accessibility - Accessibility improvements
        - Developer Experience - Tools or features for developers
        - Other
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases or scenarios where this feature would be helpful
      placeholder: |
        - Use case 1: ...
        - Use case 2: ...
        - Use case 3: ...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If you have mockups, screenshots, or examples from other applications, please share them
      placeholder: Attach any relevant images or links...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, research, or information about the feature request
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all the information requested above
          required: true
        - label: I have considered the impact on existing users
          required: true
